component: aws-dynamodb
name: database

# Note:  Replace `deploy_environment`` and `region`` variables with relative values for your needs.

inputs:
  name: Soccer-${deploy_environment}
  region: ${region}
  # Doesn't delete the Database Table if "serverless remove" is run
  deletionPolicy: retain
  attributeDefinitions:
    - AttributeName: Id
      AttributeType: S
    - AttributeName: Metadata
      AttributeType: S
    - AttributeName: PlayerName
      AttributeType: S
    - AttributeName: GameDay
      AttributeType: S
  keySchema:
    - AttributeName: Id
      KeyType: HASH
    - AttributeName: Metadata
      KeyType: RANGE
  globalSecondaryIndexes:
    - IndexName: MetadataIndex
      KeySchema:
        - AttributeName: Metadata
          KeyType: HASH
      Projection:
        ProjectionType: ALL
    - IndexName: MetadataGameIndex
      KeySchema:
        - AttributeName: Metadata
          KeyType: HASH
        - AttributeName: GameDay
          KeyType: RANGE
      Projection:
        ProjectionType: ALL
    - IndexName: MetadataPlayerIndex
      KeySchema:
        - AttributeName: Metadata
          KeyType: HASH
        - AttributeName: PlayerName
          KeyType: RANGE
      Projection:
        ProjectionType: ALL
